use std::error::Error;
use std::fmt::{self, Display, Formatter};
use std::io;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ProjectError {
    HomeUnavailable,
    InvalidProjectRoot,
    UnsafeProjectRoot,
    ProjectRootMissing,
    ProjectRootConflict,
    ProjectManifestMissing,
    ProjectManifestConflict,
    ProjectAlreadyRegistered,
    ProjectNotRegistered,
    ProjectIdentityConflict,
    InvalidProjectDocument,
    InvalidLibraryDocument,
    InvalidCaptureDocument,
    InvalidGraphDocument,
    InvalidGraphQuery,
    InvalidPortfolioCatalog,
    InvalidPortfolioQuery,
    InvalidSemanticTimeline,
    PortfolioCatalogConflict,
    GraphEntityNotFound,
    GraphArtifactNotFound,
    ProjectArtifactUnsupported,
    ProjectArtifactContentInvalid,
    CaptureNotFound,
    CaptureAlreadyApplied,
    CaptureIdentityConflict,
    InvalidResolutionDocument,
    ResolutionIdentityConflict,
    CaptureResolutionAlreadyApplied,
    CaptureResolutionConflict,
    InvalidDeliveryDocument,
    DeliveryNotFound,
    DeliveryIdentityConflict,
    InvalidDeliveryTransition,
    DeliveryAcknowledgementConflict,
    ConsolidationAlreadyApplied,
    ConsolidationConflict,
    PortablePackageInvalid,
    MigrationSourceInvalid,
    DocumentTooLarge,
    LibraryFull,
    RevisionConflict,
    PlanMismatch,
    ApprovalRequired,
    OperationCancelled,
    LockBusy,
    RecoveryRequired,
    UnsupportedPlatformSecurity,
    RandomUnavailable,
    PersistenceFailed(io::ErrorKind),
}

impl ProjectError {
    #[must_use]
    pub const fn reason_code(self) -> &'static str {
        match self {
            Self::HomeUnavailable => "project-home-unavailable",
            Self::InvalidProjectRoot => "project-root-invalid",
            Self::UnsafeProjectRoot => "project-root-unsafe",
            Self::ProjectRootMissing => "project-root-missing",
            Self::ProjectRootConflict => "project-root-conflict",
            Self::ProjectManifestMissing => "project-manifest-missing",
            Self::ProjectManifestConflict => "project-manifest-conflict",
            Self::ProjectAlreadyRegistered => "project-already-registered",
            Self::ProjectNotRegistered => "project-not-registered",
            Self::ProjectIdentityConflict => "project-identity-conflict",
            Self::InvalidProjectDocument => "project-document-invalid",
            Self::InvalidLibraryDocument => "research-library-document-invalid",
            Self::InvalidCaptureDocument => "research-capture-document-invalid",
            Self::InvalidGraphDocument => "academic-graph-document-invalid",
            Self::InvalidGraphQuery => "academic-graph-query-invalid",
            Self::InvalidPortfolioCatalog => "portfolio-catalog-document-invalid",
            Self::InvalidPortfolioQuery => "portfolio-query-invalid",
            Self::InvalidSemanticTimeline => "semantic-timeline-invalid",
            Self::PortfolioCatalogConflict => "portfolio-catalog-conflict",
            Self::GraphEntityNotFound => "academic-graph-entity-not-found",
            Self::GraphArtifactNotFound => "academic-graph-artifact-not-found",
            Self::ProjectArtifactUnsupported => "project-artifact-unsupported",
            Self::ProjectArtifactContentInvalid => "project-artifact-content-invalid",
            Self::CaptureNotFound => "research-capture-not-found",
            Self::CaptureAlreadyApplied => "research-capture-already-applied",
            Self::CaptureIdentityConflict => "research-capture-identity-conflict",
            Self::InvalidResolutionDocument => "capture-resolution-document-invalid",
            Self::ResolutionIdentityConflict => "capture-resolution-identity-conflict",
            Self::CaptureResolutionAlreadyApplied => "capture-resolution-already-applied",
            Self::CaptureResolutionConflict => "capture-resolution-conflict",
            Self::InvalidDeliveryDocument => "capture-delivery-document-invalid",
            Self::DeliveryNotFound => "capture-delivery-not-found",
            Self::DeliveryIdentityConflict => "capture-delivery-identity-conflict",
            Self::InvalidDeliveryTransition => "capture-delivery-transition-invalid",
            Self::DeliveryAcknowledgementConflict => "capture-delivery-acknowledgement-conflict",
            Self::ConsolidationAlreadyApplied => "capture-consolidation-already-applied",
            Self::ConsolidationConflict => "capture-consolidation-conflict",
            Self::PortablePackageInvalid => "portable-project-package-invalid",
            Self::MigrationSourceInvalid => "legacy-project-migration-source-invalid",
            Self::DocumentTooLarge => "project-document-too-large",
            Self::LibraryFull => "research-library-full",
            Self::RevisionConflict => "project-revision-conflict",
            Self::PlanMismatch => "project-plan-mismatch",
            Self::ApprovalRequired => "project-filesystem-approval-required",
            Self::OperationCancelled => "portfolio-operation-cancelled",
            Self::LockBusy => "project-library-lock-busy",
            Self::RecoveryRequired => "project-recovery-required",
            Self::UnsupportedPlatformSecurity => "unsupported-platform-security",
            Self::RandomUnavailable => "project-random-unavailable",
            Self::PersistenceFailed(_) => "project-persistence-failed",
        }
    }
}

impl Display for ProjectError {
    fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.reason_code())
    }
}

impl Error for ProjectError {}
