from __future__ import annotations

import copy
from datetime import date
import json
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import unittest
from unittest import mock

from scripts.validate_repository_source import (
    BASELINE_RELATIVE,
    CONTRACT_RELATIVE,
    PolicyError,
    REPO_ROOT,
    _boundary_findings,
    _decode_git_paths,
    _findings_for_baseline,
    applicable_rule_ids,
    changed_paths_from_git,
    finding_fingerprint,
    is_canonical_repository_path,
    load_baseline,
    load_contract,
    validate_repository,
)


SCRIPT = REPO_ROOT / "scripts" / "validate_repository_source.py"
CASES = REPO_ROOT / "tests" / "fixtures" / "repository_source" / "cases.json"


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _git(root: Path, *arguments: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", "-C", str(root), *arguments],
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )


def _create_policy_repo(root: Path) -> None:
    _git(root.parent, "init", "-q", str(root))
    contract_source = REPO_ROOT / CONTRACT_RELATIVE
    baseline_source = REPO_ROOT / BASELINE_RELATIVE
    contract_target = root / CONTRACT_RELATIVE
    baseline_target = root / BASELINE_RELATIVE
    contract_target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(contract_source, contract_target)
    shutil.copyfile(baseline_source, baseline_target)

    _write(
        root / "packages/qiongli-native/Cargo.toml",
        """[workspace]
resolver = "3"
members = ["apps/qiongli"]
default-members = ["apps/qiongli"]

[workspace.package]
version = "2.0.0-alpha.1"
edition = "2024"
rust-version = "1.97"
authors = ["Qiongli Test"]
license = "MIT"
repository = "https://example.invalid/qiongli"
publish = false

[workspace.metadata.qiongli]
product = "qiongli"
channel = "alpha"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
disallowed_methods = "deny"
""",
    )
    _write(
        root / "packages/qiongli-native/apps/qiongli/Cargo.toml",
        """[package]
name = "qiongli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true
""",
    )
    _write(
        root / "packages/qiongli-native/apps/qiongli/src/main.rs",
        "#![forbid(clippy::disallowed_methods)]\nfn main() {}\n",
    )
    _write(
        root / "packages/qiongli-native/Cargo.lock",
        """# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "qiongli"
version = "2.0.0-alpha.1"
""",
    )
    _write(
        root / "packages/qiongli-native/rust-toolchain.toml",
        """[toolchain]
channel = "1.97.0"
profile = "minimal"
components = ["rustfmt", "clippy"]
""",
    )
    _write(
        root / "packages/qiongli-native/clippy.toml",
        """disallowed-methods = [
  { path = "std::process::Command::new", reason = "no external runtimes" },
]
""",
    )
    _write(root / "packages/qiongli-native/.gitignore", "/target/\n")


def _validate(root: Path, *changed: str):
    return validate_repository(
        root,
        changed or ("packages/qiongli-native/apps/qiongli/src/main.rs",),
        mode="changed-files",
        today=date(2030, 1, 1),
    )


def _set_native_identity(
    root: Path, *, version: str, channel: str, lock_version: str | None = None
) -> None:
    manifest = root / "packages/qiongli-native/Cargo.toml"
    manifest_text = manifest.read_text(encoding="utf-8")
    manifest_text = manifest_text.replace(
        'version = "2.0.0-alpha.1"', f'version = "{version}"', 1
    ).replace('channel = "alpha"', f'channel = "{channel}"', 1)
    manifest.write_text(manifest_text, encoding="utf-8")

    lockfile = root / "packages/qiongli-native/Cargo.lock"
    lock_text = lockfile.read_text(encoding="utf-8").replace(
        'version = "2.0.0-alpha.1"',
        f'version = "{lock_version or version}"',
        1,
    )
    lockfile.write_text(lock_text, encoding="utf-8")


class RepositorySourceValidatorTests(unittest.TestCase):
    def test_repository_policy_and_native_workspace_pass(self) -> None:
        contract = load_contract(REPO_ROOT)
        self.assertEqual(contract["contract_id"], "RC1")
        result = validate_repository(
            REPO_ROOT,
            ["packages/qiongli-native/apps/qiongli/src/main.rs"],
            mode="changed-files",
        )
        self.assertEqual(result.findings, ())
        self.assertIn("RSC-RUST-001", result.applicable_rule_ids)

    def test_native_version_and_channel_are_derived_instead_of_hardcoded(self) -> None:
        identities = (
            ("2.0.0-alpha.2", "alpha"),
            ("2.0.0-beta.1", "beta"),
            ("2.0.0", "stable"),
        )
        for version, channel in identities:
            with self.subTest(version=version), tempfile.TemporaryDirectory() as directory:
                root = Path(directory) / "repo"
                _create_policy_repo(root)
                _set_native_identity(root, version=version, channel=channel)

                result = _validate(root, "packages/qiongli-native/Cargo.toml")

                self.assertEqual(result.findings, ())

    def test_native_channel_must_match_version_semantics(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "repo"
            _create_policy_repo(root)
            _set_native_identity(root, version="2.0.0-beta.2", channel="alpha")

            result = _validate(root, "packages/qiongli-native/Cargo.toml")

        channel_findings = [
            finding
            for finding in result.findings
            if finding.rule_id == "RSC-TOPOLOGY-001"
            and "metadata channel" in finding.message
        ]
        self.assertEqual(len(channel_findings), 1)
        self.assertIn("expected 'beta'", channel_findings[0].message)

    def test_native_lock_version_must_match_dynamic_workspace_version(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "repo"
            _create_policy_repo(root)
            _set_native_identity(
                root,
                version="2.0.0-alpha.4",
                channel="alpha",
                lock_version="2.0.0-alpha.3",
            )

            result = _validate(root, "packages/qiongli-native/Cargo.lock")

        lock_findings = [
            finding
            for finding in result.findings
            if finding.path == "packages/qiongli-native/Cargo.lock"
            and finding.rule_id == "RSC-DEPENDENCY-001"
        ]
        self.assertEqual(len(lock_findings), 1)
        self.assertIn("2.0.0-alpha.4", lock_findings[0].message)

    def test_native_manifest_rejects_legacy_or_undefined_release_channels(self) -> None:
        cases = (
            ("1.19.1-beta.1", "beta", "native 2.x release line"),
            ("2.0.0-rc.1", "rc", "version is invalid"),
        )
        for version, channel, expected_message in cases:
            with self.subTest(version=version), tempfile.TemporaryDirectory() as directory:
                root = Path(directory) / "repo"
                _create_policy_repo(root)
                _set_native_identity(root, version=version, channel=channel)

                result = _validate(root, "packages/qiongli-native/Cargo.toml")

                self.assertTrue(
                    any(expected_message in finding.message for finding in result.findings),
                    result.findings,
                )

    def test_rule_selection_is_limited_to_native_changes(self) -> None:
        docs_rules = applicable_rule_ids(["docs/development/example.md"])
        native_rules = applicable_rule_ids(
            ["packages/qiongli-native/apps/qiongli/src/main.rs"]
        )
        self.assertNotIn("RSC-RUST-001", docs_rules)
        self.assertNotIn("RSC-DEPENDENCY-001", docs_rules)
        self.assertIn("RSC-RUST-001", native_rules)
        self.assertIn("RSC-DEPENDENCY-001", native_rules)
        self.assertIn("RSC-GENERATED-001", docs_rules)

    def test_cross_platform_noncanonical_paths_are_rejected(self) -> None:
        invalid = (
            "/Users/example/source.rs",
            "/home/example/source.rs",
            "C:\\Users\\example\\source.rs",
            "\\\\server\\share\\source.rs",
            "packages/qiongli-native/../outside.rs",
            "packages\\qiongli-native\\source.rs",
            "packages//qiongli-native/source.rs",
            "./packages/qiongli-native/source.rs",
        )
        for path in invalid:
            with self.subTest(path=path):
                self.assertFalse(is_canonical_repository_path(path))
        self.assertTrue(
            is_canonical_repository_path(
                "packages/qiongli-native/apps/qiongli/src/main.rs"
            )
        )

    def test_table_driven_security_cases(self) -> None:
        fixture = json.loads(CASES.read_text(encoding="utf-8"))
        self.assertEqual(fixture["schema_version"], "1.0")
        for case in fixture["cases"]:
            with self.subTest(case=case["id"]), tempfile.TemporaryDirectory() as directory:
                root = Path(directory) / "repo"
                _create_policy_repo(root)
                _write(root / case["path"], case["content"])
                result = _validate(root, case["path"])
                actual = sorted(
                    {
                        finding.rule_id
                        for finding in result.findings
                        if finding.path == case["path"]
                    }
                )
                self.assertEqual(actual, case["expected_rule_ids"])

    def test_secret_signature_is_blocking_and_never_echoed(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "repo"
            _create_policy_repo(root)
            token = "-----BEGIN " + "PRIVATE KEY-----"
            relative = "packages/qiongli-native/testdata/id_rsa.pem"
            _write(root / relative, f"{token}\nnot-a-real-key\n")
            result = _validate(root, relative)
            report = json.dumps(result.as_report(), sort_keys=True)
        self.assertTrue(
            any(finding.rule_id == "RSC-SECURITY-001" for finding in result.findings)
        )
        self.assertNotIn(token, report)

    def test_production_rust_cannot_launch_external_processes(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "repo"
            _create_policy_repo(root)
            relative = "packages/qiongli-native/apps/qiongli/src/runtime.rs"
            _write(
                root / relative,
                'use std::process as p;\ntype Launcher = p::Command;\n'
                'fn run() { let _ = Launcher::new("node"); }\n',
            )
            result = _validate(root, relative)
        self.assertTrue(
            any(
                finding.rule_id == "RSC-RUNTIME-001"
                and finding.path == relative
                for finding in result.findings
            )
        )

    @unittest.skipUnless(shutil.which("cargo"), "cargo is unavailable")
    def test_clippy_resolves_process_command_aliases(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            workspace = Path(directory) / "qiongli-native"
            shutil.copytree(
                REPO_ROOT / "packages/qiongli-native",
                workspace,
                ignore=shutil.ignore_patterns("target"),
            )
            _write(
                workspace / "apps/qiongli/src/main.rs",
                """#![forbid(clippy::disallowed_methods)]
#![allow(clippy::disallowed_methods)]
use std as s;
use s::process as p;
type Launcher = p::Command;
fn main() { let _ = Launcher::new("node"); }
""",
            )
            completed = subprocess.run(
                [
                    "cargo",
                    "clippy",
                    "--manifest-path",
                    str(workspace / "Cargo.toml"),
                    "--workspace",
                    "--all-targets",
                    "--all-features",
                    "--locked",
                    "--",
                    "-D",
                    "warnings",
                ],
                cwd=workspace,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
        self.assertNotEqual(completed.returncode, 0)
        self.assertIn("forbid", completed.stderr.lower())

    def test_b2a_product_dependencies_and_runtime_lint_cannot_expand(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "repo"
            _create_policy_repo(root)
            manifest = root / "packages/qiongli-native/apps/qiongli/Cargo.toml"
            manifest.write_text(
                manifest.read_text(encoding="utf-8")
                + '\n[dependencies]\nserde = "1"\n',
                encoding="utf-8",
            )
            workspace = root / "packages/qiongli-native/Cargo.toml"
            workspace.write_text(
                workspace.read_text(encoding="utf-8").replace(
                    'disallowed_methods = "deny"', 'disallowed_methods = "allow"'
                ),
                encoding="utf-8",
            )
            main = root / "packages/qiongli-native/apps/qiongli/src/main.rs"
            main.write_text(
                main.read_text(encoding="utf-8").replace(
                    "#![forbid(clippy::disallowed_methods)]\n", ""
                ),
                encoding="utf-8",
            )
            result = _validate(root, manifest.relative_to(root).as_posix())
        rule_ids = {finding.rule_id for finding in result.findings}
        self.assertIn("RSC-DEPENDENCY-001", rule_ids)
        self.assertIn("RSC-RUNTIME-001", rule_ids)

    def test_cargo_config_and_rust_environment_overrides_are_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "repo"
            _create_policy_repo(root)
            root_config = ".cargo/config.toml"
            native_config = "packages/qiongli-native/.cargo/config.toml"
            override = "--cap-lints=allow"
            _write(root / root_config, f'[build]\nrustflags = ["{override}"]\n')
            _write(root / native_config, f'[build]\nrustflags = ["{override}"]\n')
            with mock.patch.dict("os.environ", {"RUSTFLAGS": override}):
                result = _validate(root, native_config)
            report = json.dumps(result.as_report(), sort_keys=True)
        runtime_paths = {
            finding.path
            for finding in result.findings
            if finding.rule_id == "RSC-RUNTIME-001"
        }
        self.assertIn(root_config, runtime_paths)
        self.assertIn(native_config, runtime_paths)
        self.assertIn("packages/qiongli-native/Cargo.toml", runtime_paths)
        self.assertNotIn(override, report)

    def test_b2a_forbids_build_scripts(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "repo"
            _create_policy_repo(root)
            manifest = root / "packages/qiongli-native/apps/qiongli/Cargo.toml"
            manifest.write_text(
                manifest.read_text(encoding="utf-8").replace(
                    'name = "qiongli"', 'name = "qiongli"\nbuild = "build.rs"', 1
                ),
                encoding="utf-8",
            )
            build_script = "packages/qiongli-native/apps/qiongli/build.rs"
            _write(root / build_script, 'fn main() { println!("cargo:warning=build"); }\n')
            result = _validate(root, build_script)
        self.assertTrue(
            any(
                finding.rule_id == "RSC-RUNTIME-001"
                and (finding.path == build_script or "build script" in finding.message)
                for finding in result.findings
            )
        )

    def test_symlink_and_tracked_build_output_are_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "repo"
            _create_policy_repo(root)
            outside = root / "outside.rs"
            _write(outside, "fn outside() {}\n")
            link = root / "packages/qiongli-native/apps/qiongli/src/link.rs"
            try:
                link.symlink_to(outside)
            except (OSError, NotImplementedError):
                self.skipTest("symlinks are unavailable")
            artifact = root / "packages/qiongli-native/target/debug/qiongli.exe"
            _write(artifact, "not a binary\n")
            _git(root, "add", "-f", "packages/qiongli-native/target/debug/qiongli.exe")
            result = _validate(root, link.relative_to(root).as_posix())
        boundary_paths = {
            finding.path
            for finding in result.findings
            if finding.rule_id == "RSC-BOUNDARY-001"
        }
        self.assertIn(link.relative_to(root).as_posix(), boundary_paths)
        self.assertIn(artifact.relative_to(root).as_posix(), boundary_paths)

    def test_escaping_path_dependency_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "repo"
            _create_policy_repo(root)
            manifest = root / "packages/qiongli-native/apps/qiongli/Cargo.toml"
            manifest.write_text(
                manifest.read_text(encoding="utf-8")
                + '\n[dependencies]\nlegacy = { path = "../../../qiongli-lite-mcp" }\n',
                encoding="utf-8",
            )
            result = _validate(root, manifest.relative_to(root).as_posix())
        self.assertTrue(
            any(
                finding.rule_id == "RSC-BOUNDARY-001"
                and "path dependency" in finding.message
                for finding in result.findings
            )
        )

    def test_windows_absolute_path_dependency_is_rejected_portably(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "repo"
            _create_policy_repo(root)
            manifest = root / "packages/qiongli-native/apps/qiongli/Cargo.toml"
            manifest.write_text(
                manifest.read_text(encoding="utf-8")
                + '\n[dependencies]\nlocal = { path = "C:\\\\Users\\\\example\\\\crate" }\n',
                encoding="utf-8",
            )
            result = _validate(root, manifest.relative_to(root).as_posix())
        self.assertTrue(
            any(
                finding.rule_id == "RSC-BOUNDARY-001"
                and "portable workspace-relative" in finding.message
                for finding in result.findings
            )
        )

    def test_second_manifest_and_auto_discovered_binary_are_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "repo"
            _create_policy_repo(root)
            _write(
                root / "packages/qiongli-native/rogue/Cargo.toml",
                '[[bin]]\nname = "rogue"\npath = "entry.rs"\n',
            )
            _write(root / "packages/qiongli-native/rogue/entry.rs", "fn main() {}\n")
            auto_bin = "packages/qiongli-native/apps/qiongli/src/bin/rogue.rs"
            _write(root / auto_bin, "fn main() {}\n")
            result = _validate(root, auto_bin)
        topology_messages = [
            finding.message
            for finding in result.findings
            if finding.rule_id == "RSC-TOPOLOGY-001"
        ]
        self.assertTrue(any("exactly the apps/qiongli" in value for value in topology_messages))
        self.assertTrue(any("auto-discovered" in value for value in topology_messages))

    def test_executable_build_output_and_gitlink_modes_are_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "repo"
            _create_policy_repo(root)
            executable = "packages/qiongli-native/dist/qiongli"
            _write(root / executable, "generated executable\n")
            (root / executable).chmod(0o755)
            gitlink = "packages/qiongli-native/vendor/external"
            findings = _boundary_findings(
                root,
                [executable, gitlink],
                {executable: "100755", gitlink: "160000"},
            )
        paths = {
            finding.path
            for finding in findings
            if finding.rule_id == "RSC-BOUNDARY-001"
        }
        self.assertEqual(paths, {executable, gitlink})

    def test_product_cannot_disable_its_only_binary_target(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "repo"
            _create_policy_repo(root)
            manifest = root / "packages/qiongli-native/apps/qiongli/Cargo.toml"
            manifest.write_text(
                manifest.read_text(encoding="utf-8").replace(
                    'name = "qiongli"', 'name = "qiongli"\nautobins = false', 1
                ),
                encoding="utf-8",
            )
            result = _validate(root, manifest.relative_to(root).as_posix())
        self.assertTrue(
            any(
                finding.rule_id == "RSC-TOPOLOGY-001"
                and "cannot disable" in finding.message
                for finding in result.findings
            )
        )

    def test_missing_lockfile_and_unsafe_lint_drift_are_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "repo"
            _create_policy_repo(root)
            (root / "packages/qiongli-native/Cargo.lock").unlink()
            manifest = root / "packages/qiongli-native/Cargo.toml"
            manifest.write_text(
                manifest.read_text(encoding="utf-8").replace(
                    'unsafe_code = "forbid"', 'unsafe_code = "allow"'
                ),
                encoding="utf-8",
            )
            result = _validate(root, manifest.relative_to(root).as_posix())
        rule_ids = {finding.rule_id for finding in result.findings}
        self.assertIn("RSC-DEPENDENCY-001", rule_ids)
        self.assertIn("RSC-UNSAFE-001", rule_ids)

    def test_baseline_rejects_native_broad_expired_and_drifted_entries(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "repo"
            _create_policy_repo(root)
            legacy = "docs/legacy.py"
            _write(root / legacy, "print('legacy')\n")
            entry = {
                "rule_id": "RSC-SECURITY-001",
                "path": legacy,
                "fingerprint": finding_fingerprint(root, "RSC-SECURITY-001", legacy),
                "owner": "maintainers",
                "rationale": "legacy debt",
                "compensating_check": "manual review",
                "expires_on": "2029-12-31",
            }
            baseline = copy.deepcopy(load_baseline(root))
            baseline["findings"] = [
                entry,
                {
                    **entry,
                    "path": "packages/qiongli-native/apps/qiongli/src/main.rs",
                    "fingerprint": finding_fingerprint(
                        root,
                        "RSC-SECURITY-001",
                        "packages/qiongli-native/apps/qiongli/src/main.rs",
                    ),
                    "expires_on": "2031-01-01",
                },
                {
                    **entry,
                    "path": "packages",
                    "fingerprint": "0" * 64,
                    "expires_on": "2031-01-01",
                },
            ]
            findings = _findings_for_baseline(root, baseline, today=date(2030, 1, 1))
        messages = [finding.message for finding in findings]
        self.assertTrue(any("expired" in message for message in messages))
        self.assertTrue(any("native-foundation debt" in message for message in messages))
        self.assertTrue(any("existing regular file" in message for message in messages))
        self.assertTrue(any("fingerprint" in message for message in messages))

    def test_baseline_fingerprint_detects_dirty_worktree_drift(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "repo"
            _create_policy_repo(root)
            _git(root, "config", "user.email", "test@example.com")
            _git(root, "config", "user.name", "Qiongli Test")
            legacy = "docs/legacy.py"
            _write(root / legacy, "print('accepted')\n")
            _git(root, "add", ".")
            _git(root, "commit", "-m", "baseline")
            entry = {
                "rule_id": "RSC-SECURITY-001",
                "path": legacy,
                "fingerprint": finding_fingerprint(root, "RSC-SECURITY-001", legacy),
                "owner": "maintainers",
                "rationale": "legacy debt",
                "compensating_check": "manual review",
                "expires_on": "2031-01-01",
            }
            _write(root / legacy, "print('dirty')\n")
            baseline = copy.deepcopy(load_baseline(root))
            baseline["findings"] = [entry]
            findings = _findings_for_baseline(root, baseline, today=date(2030, 1, 1))
        self.assertTrue(any("fingerprint" in finding.message for finding in findings))

    def test_baseline_fingerprint_detects_staged_index_divergence(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "repo"
            _create_policy_repo(root)
            _git(root, "config", "user.email", "test@example.com")
            _git(root, "config", "user.name", "Qiongli Test")
            legacy = "docs/legacy.py"
            accepted = "print('accepted')\n"
            _write(root / legacy, accepted)
            _git(root, "add", ".")
            _git(root, "commit", "-m", "baseline")
            entry = {
                "rule_id": "RSC-SECURITY-001",
                "path": legacy,
                "fingerprint": finding_fingerprint(root, "RSC-SECURITY-001", legacy),
                "owner": "maintainers",
                "rationale": "legacy debt",
                "compensating_check": "manual review",
                "expires_on": "2031-01-01",
            }
            _write(root / legacy, "print('staged')\n")
            _git(root, "add", legacy)
            _write(root / legacy, accepted)
            baseline = copy.deepcopy(load_baseline(root))
            baseline["findings"] = [entry]
            findings = _findings_for_baseline(root, baseline, today=date(2030, 1, 1))
        self.assertTrue(any("fingerprint" in finding.message for finding in findings))

    def test_non_utf8_git_path_is_a_policy_error(self) -> None:
        with self.assertRaises(PolicyError):
            _decode_git_paths(b"packages/qiongli-native/\xff.rs\0", "test")

    def test_git_diff_mode_includes_rename_as_delete_and_add(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / "repo"
            _create_policy_repo(root)
            _git(root, "config", "user.email", "test@example.com")
            _git(root, "config", "user.name", "Qiongli Test")
            _write(root / "docs/old.md", "old\n")
            _git(root, "add", ".")
            _git(root, "commit", "-m", "baseline")
            base = _git(root, "rev-parse", "HEAD").stdout.strip()
            _git(root, "mv", "docs/old.md", "docs/new.md")
            _write(
                root / "packages/qiongli-native/apps/qiongli/src/main.rs",
                "fn main() { println!(\"changed\"); }\n",
            )
            _git(root, "add", ".")
            _git(root, "commit", "-m", "change")
            changed = changed_paths_from_git(root, base)
        self.assertIn("docs/old.md", changed)
        self.assertIn("docs/new.md", changed)
        self.assertIn("packages/qiongli-native/apps/qiongli/src/main.rs", changed)

    def test_cli_emits_machine_readable_pass_and_usage_error(self) -> None:
        passed = subprocess.run(
            [
                sys.executable,
                str(SCRIPT),
                "--changed-file",
                "packages/qiongli-native/apps/qiongli/src/main.rs",
                "--json",
            ],
            cwd=REPO_ROOT,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
        self.assertEqual(passed.returncode, 0, passed.stderr)
        self.assertEqual(json.loads(passed.stdout)["status"], "passed")
        self.assertEqual(passed.stderr, "")

        invalid = subprocess.run(
            [
                sys.executable,
                str(SCRIPT),
                "--changed-file",
                "../outside.rs",
                "--json",
            ],
            cwd=REPO_ROOT,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
        self.assertEqual(invalid.returncode, 2)
        self.assertEqual(json.loads(invalid.stdout)["status"], "error")
        self.assertEqual(invalid.stderr, "")

        missing_mode = subprocess.run(
            [sys.executable, str(SCRIPT), "--json"],
            cwd=REPO_ROOT,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
        self.assertEqual(missing_mode.returncode, 2)
        self.assertEqual(json.loads(missing_mode.stdout)["status"], "error")
        self.assertEqual(missing_mode.stderr, "")


if __name__ == "__main__":
    unittest.main()
