use std::collections::BTreeMap;

use serde_json::json;

use crate::providers::search::LiteratureResult;

pub fn export_import_files(records: Vec<LiteratureResult>) -> BTreeMap<String, String> {
    let mut files = BTreeMap::new();
    files.insert("references.json".to_string(), to_csl_json(&records));
    files.insert("references.ris".to_string(), to_ris(&records));
    files.insert("bibliography.bib".to_string(), to_bibtex(&records));
    files.insert("zotero-import-report.md".to_string(), to_report(&records));
    files
}

fn to_csl_json(records: &[LiteratureResult]) -> String {
    let csl_records = records
        .iter()
        .map(|record| {
            json!({
                "type": "article-journal",
                "title": record.title,
                "DOI": record.doi,
                "container-title": record.venue,
                "issued": record.year.map(|year| json!({"date-parts": [[year]]})),
                "source": "qiongli-lite-mcp",
                "qiongli_provider": record.provider,
                "qiongli_providers": record.providers
            })
        })
        .collect::<Vec<_>>();
    serde_json::to_string_pretty(&csl_records).unwrap_or_else(|_| "[]".to_string())
}

fn to_ris(records: &[LiteratureResult]) -> String {
    records
        .iter()
        .map(|record| {
            format!(
                "TY  - JOUR\nTI  - {}\nPY  - {}\nJO  - {}\nDO  - {}\nER  -\n",
                record.title,
                record.year.map(|year| year.to_string()).unwrap_or_default(),
                record.venue.clone().unwrap_or_default(),
                record.doi.clone().unwrap_or_default()
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn to_bibtex(records: &[LiteratureResult]) -> String {
    records
        .iter()
        .enumerate()
        .map(|(index, record)| {
            format!(
                "@article{{qiongli{},\n  title = {{{}}},\n  year = {{{}}},\n  journal = {{{}}},\n  doi = {{{}}}\n}}\n",
                index + 1,
                record.title,
                record.year.map(|year| year.to_string()).unwrap_or_default(),
                record.venue.clone().unwrap_or_default(),
                record.doi.clone().unwrap_or_default()
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn to_report(records: &[LiteratureResult]) -> String {
    format!(
        "# Zotero Import Report\n\nRecords: {}\n\nGenerated by qiongli-lite-mcp.\n",
        records.len()
    )
}
